# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userregistration', '0002_manufacturer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='type',
            field=models.CharField(choices=[('M', 'Manufacturer'), ('D', 'Dealer'), ('C', 'Customer')], default='Customer', max_length=1),
        ),
    ]
