# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userregistration', '0003_auto_20180126_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={},
        ),
        migrations.AlterModelManagers(
            name='manufacturer',
            managers=[
            ],
        ),
        #migrations.AddField(
           # model_name='manufacturer',
            #name='password',
            #field=models.CharField(default='', max_length=20),
        #),
        # migrations.AddField(
        #     model_name='manufacturer',
        #     name='username',
        #     field=models.CharField(default='', max_length=15, unique=True),
        # ),
    ]
# 