# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userregistration', '0006_auto_20180130_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerInventory',
            fields=[
                ('manufacturerinventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('carcount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('manufacturerinventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.ManufacturerInventory')),
                ('model_name', models.CharField(max_length=15)),
                ('model_price', models.IntegerField()),
                ('numofunits', models.IntegerField()),
            ],
        ),
    ]
